<div class="banner_content_adaptive" id="bca6"><?php
global $GlobalShowAds;
if (!isset($GlobalShowAds) OR (!empty($GlobalShowAds) AND $GlobalShowAds)) {
################################################?>
<!-- Sector.biz.ua - Адаптивный 6 -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-7992327289662063"
     data-ad-slot="6198299461"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script><?php #############################################
} else {
	echo '<div class="cube_banner_content_adaptive h600 my-0"></div>';
}
?></div>