<div class="banner_content_adaptive my-3" id="bca1"><?php
global $GlobalShowAds;
if (!isset($GlobalShowAds) OR (!empty($GlobalShowAds) AND $GlobalShowAds)) {
################################################?>
<!-- Sector.biz.ua - Адаптивный 1 -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-7992327289662063"
     data-ad-slot="6010720911"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script><?php #############################################
} else {
	echo '<div class="cube_banner_content_adaptive h90 my-1"></div>';
}
?></div>