<div class="banner_content_adaptive my-3" id="bcaf1"><?php
global $GlobalShowAds;
if (!isset($GlobalShowAds) OR (!empty($GlobalShowAds) AND $GlobalShowAds)) {
################################################?>
<!-- Sector.biz.ua - Адаптивный Feed 1 -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-format="fluid"
     data-ad-layout-key="-gy-2c+2x-aa+ks"
     data-ad-client="ca-pub-7992327289662063"
     data-ad-slot="8357682651"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script><?php #############################################
} else {
	echo '<div class="cube_banner_content_adaptive h90 my-1"></div>';
}
?></div>