        <!-- === BEGIN BOTTOM === -->
        <div id="base" class="background-dark text-light">
            <div class="container py-4">
                <div class="row">
                    <!-- Disclaimer -->
                    <div class="col-md-6 mb-5">
                        
                    </div>
                    <!-- End Disclaimer -->
                    <!-- It's Interesting -->
                    <div class="col-sm-6 col-md-3 margin-bottom-30">
                        <h4 class="mb-2">Меню 2</h4>
                        <ul class="menu">
							<li><a href="#" title="title 1" target="_top">Menu 1</a></li>
							<li><a href="#" title="title 1" target="_top">Menu 1</a></li>
							<li><a href="#" title="title 1" target="_top">Menu 1</a></li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <!-- End It's Interesting -->
                    <!-- About Us -->
                    <div class="col-sm-6 col-md-3 margin-bottom-30">
						<h4 class="mb-2">Меню 2</h4>
						<ul class="menu">
							<li><a href="#" title="title 1" target="_top">Menu 1</a></li>
							<li><a href="#" title="title 1" target="_top">Menu 1</a></li>
							<li><a href="#" title="title 1" target="_top">Menu 1</a></li>
						</ul>
                        <div class="clearfix"></div>
                    </div>
                    <!-- End About Us -->
                </div>
            </div>
        </div>
	<?php
		include_once($_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR . 'parts' . DIRECTORY_SEPARATOR . 'footer.phtml');
	?>
	</body>
</html>
<!-- === END BOTTOM === -->