<!-- Header -->
<div id="header" style="background-position: 50% 50%; height:25%;" data-stellar-background-ratio="0.2">
	<div class="container">
		<div class="row">
		<?php
			include_once($_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR . 'parts' . DIRECTORY_SEPARATOR . 'logo.phtml');
		?>
		<?php
			include_once($_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR . 'parts' . DIRECTORY_SEPARATOR . 'topmenu.phtml');
		?>		
		</div>
	</div>
</div>
<!-- End Header -->