<!-- JS bottom -->
<!-- jQuery UI -->
<script src="/newdesign/js/jquery-ui.min.js" type="text/javascript"></script>
<!-- Popper.js -->
<script src="/newdesign/js/popper.min.js" type="text/javascript"></script>
<!-- Isotope - Portfolio Sorting -->
<!-- <script src="/newdesign/js/jquery.isotope.min.js" type="text/javascript"></script> -->
<!-- Mobile Menu - Slicknav -->
<script src="/newdesign/js/jquery.slicknav.min.js" type="text/javascript"></script>
<!-- Animate on Scroll-->
<script src="/newdesign/js/jquery.visible.min.js" charset="utf-8" type="text/javascript"></script>
<!-- Stellar Parallax -->
<script src="/newdesign/js/jquery.stellar.min.js" charset="utf-8" type="text/javascript"></script>
<!-- Sticky Div -->
<!-- <script src="/newdesign/js/jquery.sticky.js" charset="utf-8" type="text/javascript"></script> -->
<!-- Easing -->
<!-- <script src="https://cdn.jsdelivr.net/jquery.easing/1.3/jquery.easing.1.3.min.js" type="text/javascript"></script> -->
<!-- Slimbox2-->
<!-- <script src="/newdesign/js/slimbox2.js" charset="utf-8" type="text/javascript"></script> -->
<!--prettyPhoto -->
<script src="https://cdn.jsdelivr.net/prettyphoto/3.1.6/js/jquery.prettyPhoto.js" type="text/javascript" charset="utf-8"></script>
<?php
	if (isset($_SERVER["REQUEST_URI"]) AND preg_match('/^\/contact\/(.*)$/',$_SERVER["REQUEST_URI"],$rez)) {
		?><!-- Google ReCaptcha --><script src='//www.google.com/recaptcha/api.js'></script><?php
	}
?>
<!-- END JS bottom -->