<!-- JS top -->
<!-- jQuery -3.3.1 -->
<script src="/newdesign/js/jquery-3.3.1.min.js" type="text/javascript"></script>
<script src="/newdesign/js/jquery-migrate-3.0.0.min.js" type="text/javascript"></script>
<!-- Bootstrap.js -->
<script src="/newdesign/js/bootstrap.min.js" type="text/javascript"></script>
<!-- jQuery Lazy -->
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery.lazy/1.7.8/jquery.lazy.min.js"></script>
<!-- <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery.lazy/1.7.8/jquery.lazy.plugins.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery.lazy/1.7.8/plugins/jquery.lazy.picture.min.js"></script> -->
<!-- Modernizr -->
<script src="/newdesign/js/modernizr.custom.js" type="text/javascript"></script>
<!-- My & Nexus Scripts.js -->
<script src="/newdesign/js/scripts.js" type="text/javascript"></script>
<!-- AdSense -->
<script src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" type="text/javascript" async="async" defer="defer"></script>
<!-- END JS top -->