<div class="row">
	<div class="col mb-4">
		<!-- New Docs -->
		<div class="card">
			<div class="card-header">
				<h3 class="card-title">Новые статьи</h3>
			</div>
			<div class="card-body">
				<ul class="posts-list">
					<li>
						<div class="recent-post">
							<a href="">
								<img class="pull-left" src="/newdesign/img/blog/thumbs/thumb1.jpg" alt="thumb1">
							</a>
							<a href="#" class="posts-list-title">Sidebar post example</a>
							<br>
							<span class="recent-post-date">
								July 30, 2013
							</span>
						</div>
						<div class="clearfix"></div>
					</li>
					<li>
						<div class="recent-post">
							<a href="">
								<img class="pull-left" src="/newdesign/img/blog/thumbs/thumb2.jpg" alt="thumb2">
							</a>
							<a href="#" class="posts-list-title">Sidebar post example</a>
							<br>
							<span class="recent-post-date">
								July 30, 2013
							</span>
						</div>
						<div class="clearfix"></div>
					</li>
					<li>
						<div class="recent-post">
							<a href="">
								<img class="pull-left" src="/newdesign/img/blog/thumbs/thumb3.jpg" alt="thumb3">
							</a>
							<a href="#" class="posts-list-title">Sidebar post example</a>
							<br>
							<span class="recent-post-date">
								July 30, 2013
							</span>
						</div>
						<div class="clearfix"></div>
					</li>
					<li>
						<div class="recent-post">
							<a href="">
								<img class="pull-left" src="/newdesign/img/blog/thumbs/thumb4.jpg" alt="thumb4">
							</a>
							<a href="#" class="posts-list-title">Sidebar post example</a>
							<br>
							<span class="recent-post-date">
								July 30, 2013
							</span>
						</div>
						<div class="clearfix"></div>
					</li>
				</ul>
			</div>
		</div>
		<!-- End New Docs -->
	</div>
</div>
