<!-- === BEGIN TOP === -->
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="ru">
	<!--<![endif]-->
	<head>
		<!-- Title -->
		<title></title>
		<!-- Meta -->
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta http-equiv="content-language" content="ru">
		<meta name="keywords" content="">
		<meta name="description" content="">
		<meta name="author" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<meta name="revisit-after" content="10 days">
		<META name="robots" content="index, follow">
		<meta name="google-translate-customization" content="144f4e9cbe48ccea-09c0a7bace89b1d3-g127b1547667abccc-11">
		<!-- Favicon -->
		<link href="/newdesign/img/favicon.ico" rel="shortcut icon">
		<!-- Google Fonts-->
		<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i&amp;subset=cyrillic" type="text/css">
		<!-- Bootstrap Core CSS -->
		<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/bootstrap@4.1.1/dist/css/bootstrap.min.css" type="text/css">
		<!-- Template CSS -->
		<link rel="stylesheet" href="//use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
		<link rel="stylesheet" href="/newdesign/css/nexus.min.css" type="text/css">
		<link rel="stylesheet" href="/newdesign/css/jquery-ui.min.css" type="text/css">
		<link rel="stylesheet" href="//cdn.jsdelivr.net/prettyphoto/3.1.6/css/prettyPhoto.css" type="text/css" media="all" charset="utf-8">
		<link rel="stylesheet" href="/newdesign/css/my_design.css" type="text/css">
		<link rel="stylesheet" href="/newdesign/css/my_news_styles.css" type="text/css">
    </head>
    <body>
		<?php
			include_once($_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR . 'parts' . DIRECTORY_SEPARATOR . 'js_top.phtml');
		?>
		<!-- Visit Counters Top -->
		<div id="visit-counters-top" class="my-0 py-0">
			<?php
				include_once($_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR . 'parts' . DIRECTORY_SEPARATOR . 'counters_top.phtml');
			?>
		</div>
		<!-- END Visit Counters Top -->
		<?php
			include_once($_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR . 'parts' . DIRECTORY_SEPARATOR . 'social.phtml');
			include_once($_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR . 'parts' . DIRECTORY_SEPARATOR . 'header.phtml');
		?>
        <!-- === END TOP === -->