<!-- Top Menu -->
<div id="hornav" class="row text-light justify-content-between mr-0">
	<div class="col-md-auto pr-0">
		<div class="justify-content-start d-none d-lg-block d-xl-block">
			<ul id="hornavmenu" class="nav navbar-inline">
				<li class="nav-item">
					<a href="/" class="nav-link fa-home" title="На главную страницу сайта">Домой</a>
				</li>
				<li class="nav-item">
					<a href="/computer-news/" class="nav-link fa-newspaper" title="Новости на IT тематику">Новости</a>
				</li>
				<li>
					<span class="fa-shopping-cart">Магазин</span>
					<ul>
						<li class="parent">
							<span>В продаже</span>
							<ul>
								<li>
									<a href="/docs/CH341A_USB_Programmer/CH341A_USB_Programmer.phtml" class="nav-link" title="USB программаторы SPI Flash для чипов 24xx, 25xx и 93xx серии.">Программаторы SPI Flash</a>
								</li>
								<li>
									<a href="/saleparts/" class="nav-link" title="Вентиляторы для ноутбуков и другие комплектующие">Комплектующие для ноутбуков</a>
								</li>
								<li>
									<a href="/docs/ssd_hdd_caddy_optibay/ssd_hdd_caddy_optibay.phtml" class="nav-link" title="Адаптеры Optibay HDD Caddy для установки SSD и HDD дисков вместо приводов DVD в ноутбуках">Адаптеры Optibay HDD Caddy</a>
								</li>
							</ul>
						<li>
							<a href="/zakaz.php" class="nav-link" title="Инструкции по покупке товара в нашем магазине">Заказ, оплата, доставка</a>
						</li>
					</ul>
				</li>
				<li>
					<a href="/contact/" class="nav-link fa-envelope" title="Контакты с администрацией сайта">Контакты</a>
				</li>
			</ul>
		</div>
	</div>
	<div class="col-md-auto px-0 align-self-center d-none d-lg-block d-xl-block text-right">
		<form class="d-flex form-inline justify-content-end">
			<input id="searchinputfield" class="form-control mr-sm-3" type="search" placeholder="Search" aria-label="Search" disabled>
			<button class="btn btn-primary mr-xl-0 disabled" type="submit" disabled>Search</button>
		</form>
	</div>
</div>
<!-- End Top Menu -->